import { faker } from "@faker-js/faker";
import { db } from "@/db";
import schema from "@/db/schema";
import { logger } from "@/setup/logger";

if (
    Bun.env.NODE_ENV !== "development" &&
    Bun.env.NODE_ENV?.toString() !== "test"
) {
    throw new Error(
        "This script must be run in development or test environment.",
    );
}

export async function seed() {
    logger.info("Seeding tools...");
    const tools: (typeof schema.tool.$inferInsert)[] = [];
    for (let i = 0; i < 50; i++) {
        const tags = [];
        for (let j = 0; j < faker.number.int({ min: 1, max: 5 }); j++) {
            tags.push(faker.helpers.arrayElement(toolTags));
        }
        const tool: (typeof tools)[number] = {
            name: faker.helpers.arrayElement(toolNames),
            descriptionShort: faker.lorem.sentence(),
            description: faker.lorem.paragraph(),
            url: faker.helpers.arrayElement(toolWebsiteUrls),
            repositoryUrl: faker.helpers.arrayElement(toolRepositoryUrls),
            registryUrl: null,
            tags,
            backgroundImage: null,
            iconText: faker.helpers.arrayElement(toolIconIdentifier),
            license: faker.helpers.arrayElement(toolLicenses),
        };
        tools.push(tool);
    }
    await db.insert(schema.tool).values(tools);
    logger.info("Seeded tools.");
}

export const toolNames: string[] = [
    "Vuejs",
    "Reactjs",
    "Angular",
    "Nextjs",
    "Nuxtjs",
    "Laravel",
    "Adonisjs",
    "Django",
    "Flask",
    "Express",
    "Nestjs",
    "Spring",
    "Ruby on Rails",
    "Phoenix",
    "ASP.NET",
    "ASP.NET Core",
    "Hasura",
    "Strapi",
    "Wordpress",
    "Drupal",
    "Joomla",
    "Magento",
    "Shopify",
    "WooCommerce",
    "Directus",
    "Ghost",
    "Grav",
    "Jekyll",
    "Keystone",
    "Vercel",
    "Netlify",
    "Heroku",
    "Firebase",
    "DigitalOcean",
    "AWS",
    "Azure",
    "Google Cloud",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "MariaDB",
    "Redis",
    "SQLite",
    "Cassandra",
    "Elasticsearch",
    "Neo4j",
    "DynamoDB",
    "CouchDB",
    "rrule.js",
    "Luxon",
    "Moment.js",
    "Day.js",
    "date-fns",
    "React Router",
    "Vue Router",
    "React Navigation",
    "VueX",
    "React Context",
    "Apollo Client",
    "Redux",
    "MobX",
    "React Query",
];

export const toolRepositoryUrls: string[] = [
    "https://github.com/vuejs/vue",
    "https://github.com/facebook/react",
    "https://github.com/angular/angular",
    "https://github.com/vercel/next.js",
    "https://github.com/nuxt/nuxt.js",
    "https://github.com/laravel/laravel",
    "https://github.com/adonisjs/adonis-framework",
    "https://github.com/django/django",
    "https://github.com/pallets/flask",
    "https://github.com/expressjs/express",
    "https://github.com/nestjs/nest",
    "https://github.com/spring-projects/spring-framework",
    "https://github.com/rails/rails",
    "https://github.com/phoenixframework/phoenix",
    "https://github.com/dotnet/aspnetcore",
    "https://github.com/hasura/graphql-engine",
    "https://github.com/strapi/strapi",
    "https://github.com/WordPress/WordPress",
    "https://github.com/drupal/drupal",
    "https://github.com/joomla/joomla-cms",
    "https://github.com/magento/magento2",
    "https://github.com/Shopify/liquid",
    "https://github.com/woocommerce/woocommerce",
    "https://github.com/directus/directus",
    "https://github.com/TryGhost/Ghost",
    "https://github.com/getgrav/grav",
    "https://github.com/jekyll/jekyll",
    "https://github.com/keystonejs/keystone",
    "https://github.com/vercel/vercel",
    "https://github.com/netlify/netlify-cms",
    "https://github.com/heroku/heroku-buildpack-static",
    "https://github.com/firebase/firebase-tools",
    "https://github.com/digitalocean/netbox",
    "https://github.com/aws/aws-sdk-js",
    "https://github.com/Azure/azure-sdk-for-js",
    "https://github.com/googleapis/google-cloud-go",
    "https://github.com/mongodb/mongo",
    "https://github.com/postgres/postgres",
    "https://github.com/mysql/mysql-server",
    "https://github.com/mariadb/server",
    "https://github.com/redis/redis",
    "https://github.com/sqlite/sqlite",
    "https://github.com/apache/cassandra",
    "https://github.com/elastic/elasticsearch",
    "https://github.com/neo4j/neo4j",
    "https://github.com/aws/aws-sdk-js",
    "https://github.com/apache/couchdb",
    "https://github.com/rluvaton/rrule",
    "https://github.com/moment/moment",
    "https://github.com/iamkun/dayjs",
    "https://github.com/date-fns/date-fns",
    "https://github.com/ReactTraining/react-router",
    "https://github.com/vuejs/vue-router",
    "https://github.com/react-navigation/react-navigation",
    "https://github.com/vuejs/vuex",
    "https://github.com/facebook/react",
    "https://github.com/apollographql/apollo-client",
    "https://github.com/reduxjs/redux",
    "https://github.com/mobxjs/mobx",
    "https://github.com/tannerlinsley/react-query",
    "https://github.com/vercel/swr",
    "https://github.com/axios/axios",
    "https://github.com/expressjs/multer",
    "https://github.com/axios/axios",
];

export const toolWebsiteUrls: string[] = [
    "https://vuejs.org/",
    "https://reactjs.org/",
    "https://angular.io/",
    "https://nextjs.org/",
    "https://nuxtjs.org/",
    "https://laravel.com/",
    "https://adonisjs.com/",
    "https://www.djangoproject.com/",
    "https://flask.palletsprojects.com/",
    "https://expressjs.com/",
    "https://nestjs.com/",
    "https://spring.io/",
    "https://rubyonrails.org/",
    "https://www.phoenixframework.org/",
    "https://dotnet.microsoft.com/apps/aspnet",
    "https://hasura.io/",
    "https://strapi.io/",
    "https://wordpress.org/",
    "https://www.drupal.org/",
    "https://www.joomla.org/",
    "https://magento.com/",
    "https://shopify.dev/",
    "https://woocommerce.com/",
    "https://directus.io/",
    "https://ghost.org/",
    "https://getgrav.org/",
    "https://jekyllrb.com/",
    "https://www.keystonejs.com/",
    "https://vercel.com/",
    "https://www.netlifycms.org/",
    "https://www.heroku.com/",
    "https://firebase.google.com/",
    "https://www.digitalocean.com/",
    "https://aws.amazon.com/",
    "https://azure.microsoft.com/",
    "https://cloud.google.com/",
    "https://www.mongodb.com/",
    "https://www.postgresql.org/",
    "https://www.mysql.com/",
    "https://mariadb.org/",
    "https://redis.io/",
    "https://www.sqlite.org/",
    "https://cassandra.apache.org/",
    "https://www.elastic.co/",
    "https://neo4j.com/",
    "https://aws.amazon.com/",
    "https://couchdb.apache.org/",
];

export const toolTags: string[] = [
    "javascript",
    "typescript",
    "python",
    "php",
    "self-hostable",
    "open-source",
    "free",
    "paid",
    "cloud",
    "database",
    "cms",
    "framework",
    "library",
    "server",
    "client",
    "static",
    "dynamic",
    "fullstack",
    "frontend",
    "backend",
    "mobile",
    "desktop",
];

export const toolLicenses = [
    "MIT",
    "Apache-2.0",
    "GPL-3.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "LGPL-3.0",
    "LGPL-2.1",
];

export const toolIconIdentifier = [
    "vscode-icons:file-type-docker2",
    "vscode-icons:file-type-graphql",
    "vscode-icons:file-type-vue",
    "vscode-icons:file-type-reactjs",
    "vscode-icons:file-type-angular",
    "vscode-icons:file-type-ionic",
    "vscode-icons:file-type-node",
    "vscode-icons:file-type-nestjs",
    "vscode-icons:file-type-nginx",
    "vscode-icons:file-type-red",
    "vscode-icons:file-type-tailwind",
    "vscode-icons:file-type-terraform",
    "vscode-icons:file-type-mysql",
    "vscode-icons:file-type-mariadb",
    "vscode-icons:file-type-sqlite",
    "vscode-icons:file-type-kotlin",
    "vscode-icons:file-type-nuxt",
    "vscode-icons:file-type-light-next",
    "vscode-icons:file-type-git",
];
